# Generated by Django 3.0.2 on 2020-01-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistprofile', '0001_initial'),
        ('artwork', '0004_auto_20200105_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('testimony', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Active'), (1, 'Active')], default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tetsimonial', to='artistprofile.ArtistProfile')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_artwork', to='artwork.Artwork')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
