# Generated by Django 3.0.2 on 2020-01-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='artist',
        ),
    ]
