# Generated by Django 3.0.2 on 2020-01-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_email', models.EmailField(max_length=254)),
                ('contact_dropdown_options', models.IntegerField(choices=[(0, 'Appointment/Tattoo'), (1, 'Appointment/Piercing'), (2, 'Questions'), (3, 'Complaints')], default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('contact_subject', models.CharField(max_length=255)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
