# Generated by Django 3.0.2 on 2020-01-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20200103_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(default='<django.db.models.fields.CharField> tatto design', max_length=255),
        ),
    ]
