# Generated by Django 3.0.2 on 2020-01-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_auto_20200105_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(default=models.CharField(default='Artist tattoo design', max_length=255)),
        ),
    ]
