# Generated by Django 3.0.2 on 2020-01-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_testimonial_artist'),
        ('blog', '0001_initial'),
        ('artistprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='name',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='blog_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='customer_testimonials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_testimonials', to='testimonial.Testimonial'),
        ),
    ]
