# Generated by Django 3.0.2 on 2020-01-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistprofile', '0002_auto_20200105_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
