# Generated by Django 3.0.2 on 2020-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_testimonial_artist'),
        ('artwork', '0004_auto_20200105_2133'),
        ('blog', '0001_initial'),
        ('artistprofile', '0004_auto_20200105_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='artwork',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artwork',
            field=models.ManyToManyField(blank=True, null=True, related_name='artwork', to='artwork.Artwork'),
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='blog_posts',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to='blog.Post'),
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='customer_testimonials',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='customer_testimonials',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_testimonials', to='testimonial.Testimonial'),
        ),
    ]
