# Generated by Django 3.0.2 on 2020-01-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('testimonial', '0002_remove_testimonial_artist'),
        ('artwork', '0004_auto_20200105_2133'),
        ('artistprofile', '0005_auto_20200105_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='artwork',
            field=models.ManyToManyField(blank=True, null=True, to='artwork.Artwork'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='customer_testimonials',
            field=models.ManyToManyField(blank=True, null=True, to='testimonial.Testimonial'),
        ),
    ]
