# Generated by Django 3.0.2 on 2020-01-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistprofile', '0007_auto_20200105_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='slug',
            field=models.SlugField(default='coming-here-soon'),
        ),
    ]
